---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: '{{name}}-cert-manager'
      annotations:
        argocd.argoproj.io/sync-wave: '0'
    spec:
      project: default
      destination:
        server: '{{server}}'
        namespace: cert-manager
      sources:
        - repoURL: https://github.com/mixxor/argocd-cluster-essentials.git
          targetRevision: main
          ref: values
        - repoURL: https://charts.jetstack.io
          chart: cert-manager
          targetRevision: v1.19.2
          helm:
            releaseName: cert-manager
            valueFiles: [$values/values/cert-manager/values-basic.yaml]
        - repoURL: https://github.com/mixxor/argocd-cluster-essentials.git
          targetRevision: main
          path: manifests/cert-manager
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions: [CreateNamespace=true, ServerSideApply=true]
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
