---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: '{{name}}-external-secrets'
      annotations:
        argocd.argoproj.io/sync-wave: '1'
    spec:
      project: default
      destination:
        server: '{{server}}'
        namespace: external-secrets
      sources:
        - repoURL: https://github.com/mixxor/argocd-cluster-essentials.git
          targetRevision: main
          ref: values
        - repoURL: https://charts.external-secrets.io
          chart: external-secrets
          targetRevision: 1.2.1
          helm:
            releaseName: external-secrets
            valueFiles: [$values/values/external-secrets/values-basic.yaml]
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions: [CreateNamespace=true, ServerSideApply=true]
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
