---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gatus
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '2'
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: '{{name}}-gatus'
      annotations:
        argocd.argoproj.io/sync-wave: '2'
    spec:
      project: default
      destination:
        server: '{{server}}'
        namespace: gatus
      sources:
        - repoURL: https://github.com/mixxor/argocd-cluster-essentials.git
          targetRevision: main
          ref: values
        - repoURL: https://twin.github.io/helm-charts
          chart: gatus
          targetRevision: 1.4.4
          helm:
            releaseName: gatus
            valueFiles: [$values/values/gatus/values-basic.yaml]
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions: [CreateNamespace=true, ServerSideApply=true]
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
