---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: keycloak-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: '{{name}}-keycloak-operator'
      annotations:
        argocd.argoproj.io/sync-wave: '1'
    spec:
      project: default
      destination:
        server: '{{server}}'
        namespace: keycloak
      sources:
        # Official Keycloak Operator manifests from upstream
        - repoURL: https://github.com/keycloak/keycloak-k8s-resources.git
          targetRevision: 26.5.1
          path: kubernetes
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions: [CreateNamespace=true, ServerSideApply=true]
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
